/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-01-16 at 14:32:37 UTC 
 * Modify at your own risk.
 */
package com.campusconnect.communicator.models;

import com.google.gson.annotations.SerializedName;

/**
 * Model definition for ModelsPersonalResponse.
 * <p/>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the clubs. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class ModelsPersonalResponse {

    /**
     * The value may be {@code null}.
     */
    @SerializedName("batch")
    private java.lang.String batch;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("branch")
    private java.lang.String branch;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("name")
    private java.lang.String name;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("photoUrl")
    private java.lang.String photoUrl;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("pid")
    private java.lang.String pid;


    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }


    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getBatch() {
        return batch;
    }

    /**
     * @param batch batch or {@code null} for none
     */
    public ModelsPersonalResponse setBatch(java.lang.String batch) {
        this.batch = batch;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getBranch() {
        return branch;
    }

    /**
     * @param branch branch or {@code null} for none
     */
    public ModelsPersonalResponse setBranch(java.lang.String branch) {
        this.branch = branch;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * @param name name or {@code null} for none
     */
    public ModelsPersonalResponse setName(java.lang.String name) {
        this.name = name;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * @param photoUrl photoUrl or {@code null} for none
     */
    public ModelsPersonalResponse setPhotoUrl(java.lang.String photoUrl) {
        this.photoUrl = photoUrl;
        return this;
    }

}
