/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-01-16 at 14:32:37 UTC 
 * Modify at your own risk.
 */

package com.campusconnect.communicator.models;

import com.google.gson.annotations.SerializedName;

/**
 * Model definition for ModelsAdminStatus.
 * <p/>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the clubs. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class ModelsAdminStatus {

    /**
     * The value may be {@code null}.
     */
    @SerializedName("isAdmin")
    private java.lang.String isAdmin;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("isSuperAdmin")
    private java.lang.String isSuperAdmin;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getIsAdmin() {
        return isAdmin;
    }

    /**
     * @param isAdmin isAdmin or {@code null} for none
     */
    public ModelsAdminStatus setIsAdmin(java.lang.String isAdmin) {
        this.isAdmin = isAdmin;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getIsSuperAdmin() {
        return isSuperAdmin;
    }

    /**
     * @param isSuperAdmin isSuperAdmin or {@code null} for none
     */
    public ModelsAdminStatus setIsSuperAdmin(java.lang.String isSuperAdmin) {
        this.isSuperAdmin = isSuperAdmin;
        return this;
    }


}
