/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-01-08 17:48:37 UTC)
 * on 2016-01-16 at 14:32:37 UTC 
 * Modify at your own risk.
 */

package com.campusconnect.communicator.models;

import com.google.gson.annotations.SerializedName;

/**
 * Model definition for ModelsClubJoinResponse.
 * <p/>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the clubs. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class ModelsClubJoinResponse {

    /**
     * The value may be {@code null}.
     */
    @SerializedName("clubName")
    private java.lang.String clubName;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("fromBatch")
    private java.lang.String fromBatch;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("fromBranch")
    private java.lang.String fromBranch;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("fromName")
    private java.lang.String fromName;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("fromPhotoUrl")
    private java.lang.String fromPhotoUrl;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("fromPid")
    private java.lang.String fromPid;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("requestId")
    private java.lang.String requestId;

    /**
     * The value may be {@code null}.
     */
    @SerializedName("timestamp")
    private java.lang.String timestamp;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getClubName() {
        return clubName;
    }

    /**
     * @param clubName clubName or {@code null} for none
     */
    public ModelsClubJoinResponse setClubName(java.lang.String clubName) {
        this.clubName = clubName;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getFromBatch() {
        return fromBatch;
    }

    /**
     * @param fromBatch fromBatch or {@code null} for none
     */
    public ModelsClubJoinResponse setFromBatch(java.lang.String fromBatch) {
        this.fromBatch = fromBatch;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getFromBranch() {
        return fromBranch;
    }

    /**
     * @param fromBranch fromBranch or {@code null} for none
     */
    public ModelsClubJoinResponse setFromBranch(java.lang.String fromBranch) {
        this.fromBranch = fromBranch;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getFromName() {
        return fromName;
    }

    /**
     * @param fromName fromName or {@code null} for none
     */
    public ModelsClubJoinResponse setFromName(java.lang.String fromName) {
        this.fromName = fromName;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getFromPhotoUrl() {
        return fromPhotoUrl;
    }

    /**
     * @param fromPhotoUrl fromPhotoUrl or {@code null} for none
     */
    public ModelsClubJoinResponse setFromPhotoUrl(java.lang.String fromPhotoUrl) {
        this.fromPhotoUrl = fromPhotoUrl;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getFromPid() {
        return fromPid;
    }

    /**
     * @param fromPid fromPid or {@code null} for none
     */
    public ModelsClubJoinResponse setFromPid(java.lang.String fromPid) {
        this.fromPid = fromPid;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getRequestId() {
        return requestId;
    }

    /**
     * @param requestId requestId or {@code null} for none
     */
    public ModelsClubJoinResponse setRequestId(java.lang.String requestId) {
        this.requestId = requestId;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getTimestamp() {
        return timestamp;
    }

    /**
     * @param timestamp timestamp or {@code null} for none
     */
    public ModelsClubJoinResponse setTimestamp(java.lang.String timestamp) {
        this.timestamp = timestamp;
        return this;
    }

}
